// ZenStack CLI plugin: emits a Jazz CoValue schema (co.map/co.list, jazz-tools'
// `z`) from the same ZModel schema used to generate the ZenStack/Prisma
// client. See ../../PLAN.md M2 and ../../docs/plugin-api-notes.md.
//
// NOTE ON CONFIDENCE: the ZenStack AST/plugin API used below (CliPlugin,
// ModelUtils, DataField shapes) was verified against the installed
// @zenstackhq/sdk@3.9.3 / @zenstackhq/language@3.9.3 type
// declarations, and the jazz-tools output (co.map/co.list/z.*, `.optional()`
// chaining) has been round-trip verified: `examples/pos-inventory-demo`
// runs this plugin via the real `zen` CLI and the resulting
// generated/jazz-schema.ts type-checks against a real jazz-tools@0.20.19
// install (`tsc --strict --skipLibCheck`). See docs/plugin-api-notes.md.

import fs from 'node:fs';
import path from 'node:path';
import type { CliPlugin } from '@zenstackhq/sdk';
import { buildIr, type IrEnum, type IrField } from '@mdht/generator-core';

const SCALAR_TO_ZOD: Record<string, string> = {
  String: 'z.string()',
  Int: 'z.number()',
  Float: 'z.number()',
  Boolean: 'z.boolean()',
  DateTime: 'z.date()',
  BigInt: 'z.number() /* TODO: precision loss, no jazz-tools bigint primitive confirmed yet */',
  Decimal: 'z.number() /* TODO: precision loss, no jazz-tools decimal primitive confirmed yet */',
  Bytes: 'z.string() /* TODO: no jazz-tools bytes primitive confirmed yet */',
  Json: 'z.unknown()',
  Unsupported: 'z.unknown() /* unsupported database-native type */',
};

function enumValuesConstName(enumName: string): string {
  return `${enumName}Values`;
}

function fieldToJazzLine(field: IrField): string {
  if (field.kind === 'relation') {
    const ref = field.isList ? `co.list(${field.relationTarget})` : field.relationTarget;
    const wrapped = field.isOptional ? `co.optional(${ref})` : ref;
    // getter form so field declaration order never breaks circular/forward
    // references between models (mirrors jazz-tools' own docs pattern)
    return `  get ${field.name}() { return ${wrapped}; },`;
  }

  if (field.kind === 'enum') {
    const base = `z.enum(${enumValuesConstName(field.enumName)})`;
    const withArray = field.isList ? `z.array(${base})` : base;
    const withOptional = field.isOptional ? `${withArray}.optional()` : withArray;
    return `  ${field.name}: ${withOptional},`;
  }

  const base = SCALAR_TO_ZOD[field.scalarType] ?? 'z.unknown() /* TODO: unmapped scalar type */';
  const withArray = field.isList ? `z.array(${base})` : base;
  const withOptional = field.isOptional ? `${withArray}.optional()` : withArray;
  return `  ${field.name}: ${withOptional},`;
}

function enumToConst(e: IrEnum): string {
  const values = e.values.map((v) => `'${v}'`).join(', ');
  return `export const ${enumValuesConstName(e.name)} = [${values}] as const;\n` + `export type ${e.name} = (typeof ${enumValuesConstName(e.name)})[number];`;
}

const plugin: CliPlugin = {
  name: 'Jazz Schema Bridge',
  statusText: 'Generating Jazz CoValue schema',

  generate: ({ model, defaultOutputPath, pluginOptions }) => {
    const ir = buildIr(model);

    const outFile =
      typeof pluginOptions.output === 'string'
        ? pluginOptions.output
        : path.join(defaultOutputPath, 'jazz-schema.ts');

    const lines: string[] = [];
    lines.push('// AUTO-GENERATED by @mdht/plugin-jazz-schema. Do not edit by hand.');
    lines.push("import { co, z } from 'jazz-tools';");
    lines.push('');

    for (const e of ir.enums) {
      lines.push(enumToConst(e));
      lines.push('');
    }

    for (const m of ir.models) {
      lines.push(`export const ${m.name} = co.map({`);
      for (const f of m.fields) {
        lines.push(fieldToJazzLine(f));
      }
      lines.push('});');
      lines.push('');
    }

    const resolvedOutFile = path.isAbsolute(outFile) ? outFile : path.resolve(defaultOutputPath, outFile);
    fs.mkdirSync(path.dirname(resolvedOutFile), { recursive: true });
    fs.writeFileSync(resolvedOutFile, lines.join('\n') + '\n', 'utf-8');
  },
};

export default plugin;
