//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { schema as $schema, type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
export type StaffMember = $ModelResult<$Schema, "StaffMember">;
export type InventoryItem = $ModelResult<$Schema, "InventoryItem">;
export type Order = $ModelResult<$Schema, "Order">;
export type OrderLineItem = $ModelResult<$Schema, "OrderLineItem">;
export type WarehouseBin = $ModelResult<$Schema, "WarehouseBin">;
export const Role = $schema.enums.Role.values;
export type Role = (typeof Role)[keyof typeof Role];
