//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, type AttributeApplication, type FieldDefault, ExpressionUtils } from "@zenstackhq/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "sqlite"
    } as const;
    models = {
        StaffMember: {
            name: "StaffMember",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                role: {
                    name: "role",
                    type: "Role"
                }
            },
            attributes: [
                { name: "@@auth" }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        InventoryItem: {
            name: "InventoryItem",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                name: {
                    name: "name",
                    type: "String"
                },
                quantityOnHand: {
                    name: "quantityOnHand",
                    type: "Int"
                },
                lineItems: {
                    name: "lineItems",
                    type: "OrderLineItem",
                    array: true,
                    relation: { opposite: "inventoryItem" }
                }
            },
            attributes: [
                { name: "@@tsRestContract" },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("read") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.call("auth"), "!=", ExpressionUtils._null()) }] },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("create,update,delete") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.member(ExpressionUtils.call("auth"), ["role"]), "==", ExpressionUtils.literal("MANAGER")) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Order: {
            name: "Order",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                status: {
                    name: "status",
                    type: "String"
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("now") as FieldDefault
                },
                lineItems: {
                    name: "lineItems",
                    type: "OrderLineItem",
                    array: true,
                    relation: { opposite: "order" }
                }
            },
            attributes: [
                { name: "@@tsRestContract" },
                { name: "@@allow", args: [{ name: "operation", value: ExpressionUtils.literal("all") }, { name: "condition", value: ExpressionUtils.binary(ExpressionUtils.call("auth"), "!=", ExpressionUtils._null()) }] }
            ] as readonly AttributeApplication[],
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        OrderLineItem: {
            name: "OrderLineItem",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }] as readonly AttributeApplication[],
                    default: ExpressionUtils.call("cuid") as FieldDefault
                },
                quantity: {
                    name: "quantity",
                    type: "Int"
                },
                order: {
                    name: "order",
                    type: "Order",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("orderId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "lineItems", fields: ["orderId"], references: ["id"] }
                },
                orderId: {
                    name: "orderId",
                    type: "String",
                    foreignKeyFor: [
                        "order"
                    ] as readonly string[]
                },
                inventoryItem: {
                    name: "inventoryItem",
                    type: "InventoryItem",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("inventoryItemId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }] as readonly AttributeApplication[],
                    relation: { opposite: "lineItems", fields: ["inventoryItemId"], references: ["id"] }
                },
                inventoryItemId: {
                    name: "inventoryItemId",
                    type: "String",
                    foreignKeyFor: [
                        "inventoryItem"
                    ] as readonly string[]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        WarehouseBin: {
            name: "WarehouseBin",
            fields: {
                warehouseId: {
                    name: "warehouseId",
                    type: "String",
                    id: true
                },
                binNumber: {
                    name: "binNumber",
                    type: "Int",
                    id: true
                },
                label: {
                    name: "label",
                    type: "String"
                },
                note: {
                    name: "note",
                    type: "String",
                    optional: true
                }
            },
            attributes: [
                { name: "@@id", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("warehouseId"), ExpressionUtils.field("binNumber")]) }] },
                { name: "@@tsRestContract" }
            ] as readonly AttributeApplication[],
            idFields: ["warehouseId", "binNumber"],
            uniqueFields: {
                warehouseId_binNumber: { warehouseId: { type: "String" }, binNumber: { type: "Int" } }
            }
        }
    } as const;
    enums = {
        Role: {
            name: "Role",
            values: {
                CASHIER: "CASHIER",
                MANAGER: "MANAGER"
            }
        }
    } as const;
    authType = "StaffMember" as const;
    plugins = {};
}
export const schema = new SchemaType();
