// ZenStack CLI plugin: emits a BetterAuth `additionalFields` config (plus
// the underlying enum-as-const/type) for every enum-typed field on the
// model ZenStack resolves as `auth()`'s type -- i.e. the same model/field
// ZModel `@@allow`/`@@deny` policies read via `auth().<field>`. That's the
// "one enum drives both authorization systems" claim from PLAN.md M4.
//
// CONFIDENCE NOTE: BetterAuth's `DBFieldType` (from `@better-auth/core/db`)
// is `"string" | "number" | "boolean" | "date" | "json" | \`${string|number}[]\`
// | Array<LiteralString>` -- confirmed by installing `better-auth@1.7.3` in
// a scratch dir and reading its compiled .d.mts directly. The
// `Array<LiteralString>` arm is what lets a field's `type` be a literal
// string union (an enum), not just "string". `DBFieldAttribute` also has a
// `validator: { input?, output?: StandardSchemaV1 }` slot, so this plugin
// reuses the exact same `Schema.standardSchemaV1(...)` bridge
// `plugin-ts-rest-contract` uses for ts-rest -- one validation language
// (Effect Schema) feeding both the API boundary and the auth boundary.
//
// `@@auth` itself (unlike `@@allow`/`@@deny`) is a core ZModel attribute,
// not something `@zenstackhq/plugin-policy` contributes -- confirmed in
// @zenstackhq/language's stdlib.zmodel (`attribute @@auth()` has no plugin
// namespace prefix). `ModelUtils.getAuthDecl` implements the full
// resolution ZenStack itself uses (`@@auth`-annotated decl, else a model
// literally named "User"), so this plugin doesn't reimplement that fallback.

import fs from 'node:fs';
import path from 'node:path';
import type { CliPlugin } from '@zenstackhq/sdk';
import { ModelUtils } from '@zenstackhq/sdk';
import { isDataModel } from '@zenstackhq/language/ast';
import { buildIr } from '@codegen-bridge/generator-core';

const plugin: CliPlugin = {
  name: 'BetterAuth Claims Bridge',
  statusText: 'Generating BetterAuth claims',

  generate: ({ model, defaultOutputPath, pluginOptions }) => {
    const authDecl = ModelUtils.getAuthDecl(model);

    if (!authDecl || !isDataModel(authDecl)) {
      // No @@auth-resolvable model, or it resolved to a `type` (TypeDef)
      // rather than a `model` (DataModel) -- TypeDef auth targets aren't
      // supported yet, see docs/plugin-api-notes.md.
      return;
    }

    const ir = buildIr(model);
    const irAuthModel = ir.models.find((m) => m.name === authDecl.name);
    if (!irAuthModel) return; // unreachable: every DataModel has a matching IrModel

    const enumFields = irAuthModel.fields.filter((f) => f.kind === 'enum');
    if (enumFields.length === 0) return; // nothing enum-typed to bridge

    const usedEnumNames = new Set(enumFields.map((f) => f.enumName));
    const enumsToEmit = ir.enums.filter((e) => usedEnumNames.has(e.name));

    const outFile =
      typeof pluginOptions.output === 'string'
        ? pluginOptions.output
        : path.join(defaultOutputPath, 'betterauth-claims.ts');

    const lines: string[] = [];
    lines.push('// AUTO-GENERATED by @codegen-bridge/plugin-betterauth-claims. Do not edit by hand.');
    lines.push("import type { DBFieldAttribute } from '@better-auth/core/db';");
    lines.push("import { Schema } from 'effect';");
    lines.push('');

    for (const e of enumsToEmit) {
      const values = e.values.map((v) => `'${v}'`).join(', ');
      lines.push(`export const ${e.name}Values = [${values}] as const;`);
      lines.push(`export type ${e.name} = (typeof ${e.name}Values)[number];`);
      lines.push(`const ${e.name}StandardSchema = Schema.standardSchemaV1(Schema.Literal(...${e.name}Values));`);
      lines.push('');
    }

    for (const f of enumFields) {
      lines.push(`export const ${f.name}Field = {`);
      lines.push(`  type: [...${f.enumName}Values],`);
      lines.push('  input: false, // set server-side only -- never trust a self-reported role from user input');
      if (f.isOptional) lines.push('  required: false,');
      lines.push(`  validator: { input: ${f.enumName}StandardSchema, output: ${f.enumName}StandardSchema },`);
      lines.push('} satisfies DBFieldAttribute;');
      lines.push('');
    }

    lines.push('/**');
    lines.push(` * Spread into betterAuth({ user: { additionalFields } }) -- see`);
    lines.push(' * ../../../PLAN.md M4 for why this and the ZModel `@@allow`/`auth()`');
    lines.push(` * side both trace back to the same \`${authDecl.name}\` model's enum fields.`);
    lines.push(' */');
    lines.push('export const additionalFields = {');
    for (const f of enumFields) {
      lines.push(`  ${f.name}: ${f.name}Field,`);
    }
    lines.push('} satisfies Record<string, DBFieldAttribute>;');

    const resolvedOutFile = path.isAbsolute(outFile) ? outFile : path.resolve(defaultOutputPath, outFile);
    fs.mkdirSync(path.dirname(resolvedOutFile), { recursive: true });
    fs.writeFileSync(resolvedOutFile, lines.join('\n') + '\n', 'utf-8');
  },
};

export default plugin;
